defaults: &defaults
    working_directory: ~/repo
    docker:
        # specify the version you desire here
        - image: circleci/node:10.15.3-browsers

version: 2
jobs:
    deploy:
        <<: *defaults
        steps:
            - run:
                  name: "Show npm and node versions"
                  command: |
                      node --version
                      npm --version
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run: npm install
            - run:
                  name: "Ignore https to http switches on circleci in package lock (not sure why this happens)"
                  command: "git diff --exit-code package-lock.json || sed -i 's/http:/https:/g' package-lock.json"
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: "Run build"
                  command: "npm run build"
            - run:
                  name: "Run next export"
                  command: "npm run export"
            - run:
                  name: Deploy Master to Firebase
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
    version: 2
    deplyoment:
        jobs:
            - deploy:
                  filters:
                      branches:
                          only: master
